services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
  db:
    container_name: db
    ports:
      - 5432:5432
    image: postgres:latest
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=Asia/Jakarta
    volumes:
      - ./docker-dev-volumes/pg_data:/var/lib/postgresql/data  # Persist PostgreSQL data
  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: minioBRIN # Ganti sesuai kebutuhan
      MINIO_ROOT_PASSWORD: minioBRIN # Ganti sesuai kebutuhan
    ports:
      - "9000:9000" # Port API MinIO
      - "9001:9001" # Port Konsol Admin
    volumes:
      - ./docker-dev-volumes/minio_data:/data # Volume untuk menyimpan data
      - ./docker-dev-volumes/minio_config:/root/.minio # Volume untuk menyimpan konfigurasi
    command: server /data --console-address ":9001"
  openproject:
    image: openproject/openproject:15
    ports:
      - "8080:80"
    environment:
      OPENPROJECT_SECRET_KEY_BASE: "secret"
      OPENPROJECT_HOST__NAME: "localhost:8080"
      OPENPROJECT_HTTPS: "false"
      OPENPROJECT_DEFAULT__LANGUAGE: "en"
      OPENPROJECT_DB_URL: "postgresql://postgres:postgres@db:5432/db_openproject"  # PostgreSQL connection URL
    restart: unless-stopped
    volumes:
      - ./docker-dev-volumes/openproject-data:/var/openproject  # Persist OpenProject data (attachments, logs, etc.
    depends_on:
      - db
  sso:
    container_name: sso
    build: 
      context: sso
      dockerfile: Dockerfile
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/db_sso
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HOSTNAME=host.docker.internal
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_LOG_LEVEL=DEBUG
      - TZ=Asia/Jakarta
    ports:
      - "8443:8443"  # Port Host:Port Container
    depends_on:
      - db
  backend:
    build:
      context: .
      dockerfile: Dockerfile-dev-backend
    ports:
      - 81:3000
    tty: true
    volumes:
      - ./backend:/app
      - /app/node_modules